services:
  # 1. Database to store MLflow metadata
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "mlflow" ]
      interval: 5s
      retries: 5

  # 2. S3 Storage (MinIO) to store model artifacts
  minio:
    image: cgr.dev/chainguard/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"

  # 3. Automatically create 'mlflow' bucket in MinIO
  create-bucket:
    image: amazon/aws-cli:latest
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "sleep 5; aws --endpoint-url http://minio:9000 s3 mb s3://mlflow || echo 'Bucket already exists'"

  # 4. MLflow Tracking Server
  mlflow:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: >
      mlflow server --backend-store-uri postgresql://mlflow:mlflow_password@postgres:5432/mlflow_db --default-artifact-root s3://mlflow --host 0.0.0.0
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      postgres:
        condition: service_healthy

  # 5. Prediction Service (Credit Risk API)
  api:
    image: ghcr.io/quandd1792000/credit-risk-api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MODEL_NAME=credit_risk_classifier # Model name matching training phase
      - MODEL_STAGE=Production
    depends_on:
      - mlflow

  # 6. Data Drift Monitoring Service (Evidently)
  evidently:
    image: ghcr.io/quandd1792000/credit-risk-evidently:latest
    build:
      context: .
      dockerfile: evidently/Dockerfile
    ports:
      - "8001:8001"

  # 7. Metrics Server (Prometheus)
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"

  # 8. Dashboard (Grafana)
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # 9. Alertmanager (Discord Alerts)
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    # 10. Tự động cập nhật CD (Watchtower)
  watchtower:
    image: containrrr/watchtower
    environment:
      - DOCKER_API_VERSION=1.41
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 api evidently
    # (--interval 60 nghĩa là cứ 60 giây nó sẽ lên kiểm tra Github 1 lần. 
    # 'api evidently' là tên 2 service nó cần theo dõi để tự động update)


  # 11. Airflow Orchestration
  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    command: standalone
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - _AIRFLOW_DB_UPGRADE=True
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin123
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    depends_on:
      - mlflow
